version: '3.8'
services:
  mongodb:
    image: mongo:6-jammy
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345678
      MONGO_INITDB_DATABASE: messagesdb
    command:
      - '--logpath'
      - '/var/log/mongodb/mongod.log'
volumes:
  dbdata6:
# docker exec -it some-mongo bash